project 'XCDYouTubeKit Demo.xcodeproj'
workspace '../XCDYouTubeKit Demo.xcworkspace'

inhibit_all_warnings!

def import_pods
  pod 'XCDLumberjackNSLogger', '~> 1.0'
end

target 'XCDYouTubeKit iOS Demo' do
  platform :ios, '7.0'
  import_pods
end

target 'XCDYouTubeKit OS X Demo' do
  platform :osx, '10.9'
  import_pods
end

target 'XCDYouTubeKit tvOS Demo' do
  platform :tvos, '9.0'
  pod 'GoogleAPIClientForREST/YouTube', '~> 1.5'
end
